### ISSUE TITLE
Can I change the logo on the login page together?

### ISSUE THREAD

**Issue by wish-cloud** [Formfeed-UK/nova-logo-url#1]
The logo on the login page has not changed, can it be synchronized with the settings?

**Comment by CodeWithDennis** [comment]
I was actually wondering the same!

> The logo on the login page has not changed, can it be synchronized with the settings?

**Comment by ianrobertsFF** [comment]
Unfortunately not, Nova only loads its packages after login. The only way to get it to load JS pre-login is to put your own `layout.blade.php` in your resources folder loading custom JS, its usually easier to just override the nova login route and use breeze or similar.
